apiVersion: apps/v1
kind: Deployment
metadata:
  name: dianchi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dianchi
  template:
    metadata:
      labels:
        app: dianchi
    spec:
      imagePullSecrets:
        - name: azurecrkey
      containers:
        - name: dianchi
          image: dianchi.azurecr.cn/dianchi:latest
          ports:
            - containerPort: 80
          volumeMounts: 
            - mountPath: /app/config
              name: config
      volumes:
        - configMap:
            name: dianchi
          name: config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
        - name: pgadmin
          image: dpage/pgadmin4:latest
          ports:
            - containerPort: 80
          env:
            - name: PGADMIN_DEFAULT_EMAIL
              value: admin@dianchi.com
            - name: PGADMIN_DEFAULT_PASSWORD
              value: P@ssw0rd
