apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: dianchi
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*"
---
apiVersion: v1
kind: Service
metadata:
  name: dianchi
spec:
  selector:
    app: dianchi
  ports:
    - port: 80
---
apiVersion: v1
kind: Service
metadata:
  name: pgadmin
spec:
  selector:
    app: pgadmin
  ports:
    - port: 80
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: dianchi
spec:
  hosts:
    - "www.dianchi.corp"
    - "dianchi.corp"
  gateways:
    - dianchi
  http:  
    - route:
        - destination:
            host: dianchi
            port:
              number: 80
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: pgadmin
spec:
  hosts:
    - "pgadmin.dianchi.corp"
  gateways:
    - dianchi
  http:   
    - route:
        - destination:
            host: pgadmin
            port:
              number: 80